### ISSUE TITLE
Make it possible to use an existing client side model Id to create new model

### ISSUE THREAD

**Issue by alexmasita** [rmmmp/ember-cloud-firestore-adapter#36]
In firebase client libraries, it is possible to use for instance a user id as the id on multiple objects containing that user's information.

In this particular case, I find myself wanting to extend firebase auth object with additional attributes and it would be nice to pick the user id from the session object and create a profile document whose id is the same as the current session's user id.  

Is there a way to do it currently when creating a new model via `get(this, 'store').createRecord('profile',{})` where you can pass the current session user id as the profile model id?

**Comment by alexmasita** [comment]
That is super.  Now, how about in the batch writes?  In the previous api before you did the updates, you could pass the newly created model id on all references in the batch before updating the batch.  How would you do this now?

Many thanks for your prompt reply.  And absolutely fantastic library.

**Comment by rmmmp** [comment]
@alexmasita It's similar to the [JS SDK Batch API](https://firebase.google.com/docs/firestore/manage-data/transactions#batched-writes).

In your example above, `doc('user_a')` will indicate that `user_a` will be your ID so passing in the `id: <id here as well?>` is unnecessary as it would be equivalent to

```json
"user_a": {
  "id": "<your unnecessarily passed-in ID>",
  "body": "New Post Body",
  "title": "New Post Title",
  "author": user,
}
```

Not passing anything in the `doc()` will auto generate an ID as explained in the last [here](https://firebase.google.com/docs/firestore/manage-data/add-data#add_a_document).

**Comment by alexmasita** [comment]
Fantastic.  Will explore.
