### ISSUE TITLE
"Broccoli Builder ran into an error with `Concat` plugin"

### ISSUE THREAD

**Issue by bnetter** [rmmmp/ember-cloud-firestore-adapter#38]
Hey @rmmmp, I get an error with a fresh install of your plugin:

```
Build Canceled: Broccoli Builder ran into an error with `Concat` plugin. ðŸ’¥ ENOENT: no such file or directory, open '/Users/Benjamin/Sites/my-project/tmp/source_map_concat-input_base_path-XIEBNak7.tmp/node_modules/firebase/firebase.js'
```

I tried a basic `rm -rf node_modules` + `yarn install` but it didn't do it. Do you have any ideas why? To me it looks like it's not linking well with `ember-firebase-service`.

I didn't have the problem in `0.2.0`.

**Comment by bnetter** [comment]
I wish I could but Emberfire is still not working with Firebase 4 (and the Firestore)…

**Comment by rmmmp** [comment]
@bnetter, this is working fine for me on a fresh app.

```console
DEBUG: -------------------------------
DEBUG: Ember      : 3.0.0
DEBUG: Ember Data : 3.0.2
DEBUG: jQuery     : 3.3.1
DEBUG: -------------------------------
```

What version of Ember and Ember Data are you using? May I also see the dependencies and devDependencies of your apps if possible?

**Comment by bnetter** [comment]
Hey @rmmmp thank you for your reply! I actually had `firebase-tools` as a dependency in my `package.json`. I removed it and installed globally, now everything works perfectly.

Thanks for the good work!
