### ISSUE TITLE
"The behavior for Date objects stored in Firestore is going to change"

### ISSUE THREAD

**Issue by bnetter** [rmmmp/ember-cloud-firestore-adapter#43]
Hey, I get this error in production. Am I the only one?

<img width="552" alt="capture d ecran 2018-04-23 a 23 54 33" src="https://user-images.githubusercontent.com/336674/39155305-bca84a14-4751-11e8-8dd9-bf963dbb48d7.png">

**Comment by rmmmp** [comment]
Seems like it's a deprecation from the Firebase 4.13 version. I'll continue to work as it's just a warning. I'll push a fix soon.

**Comment by douweh** [comment]
@rmmmp I have a PR #48 open which fixes this (and makes the firestore instance a singleton)
