### ISSUE TITLE
Model a subcollection

### ISSUE THREAD

**Issue by jernejc** [rmmmp/ember-cloud-firestore-adapter#45]
Hi,

thanks for the handy adapter.

I've stumbled upon a problem while trying to model a document with a subcollection. I tried using a hasMany relationship, but it seems like it's always searching for a root collection?

```
export default DS.Model.extend({
    fragments: hasMany('fragment') // this should be a subcolletion in firestore
});
```

Is there a way to access a subcollection in a oneToMany relationship ?

**Comment by rmmmp** [comment]
As explained in the [guides](https://github.com/rmmmp/ember-cloud-firestore-adapter/blob/master/guides/01-data-structure.md), one-to-many relationships are being looked up in the `belongsTo` side. If this is a many-to-many or many-to-none relationship, it'll be looked up in a sub-collection.

What you can do is

```javascript
export default DS.Model.extend({
  fragments: hasMany('fragment', {
    inverse: null,

    // This hook will only be fired when the relationship is a many-to-many or many-to-none relationship.
    // Since you've indicated that you have a one-to-many relationship, you'll need the inverse: null above to make it many-to-none.
    buildReference(db, record) {
      return db.collection('foobar').doc(record.get('id')).collection('fragments');
    }
  })
});
```

**Comment by rmmmp** [comment]
What version of `ember-cloud-firestore-adapter` are you using? The `buildReference()` hook for `hasMany` has only been introduced in v0.3.0.

**Comment by jernejc** [comment]
After updating I see buildReference firing, but the 2nd params "record" comes in as undefined.
Using it as suggested:
```fragments: hasMany('fragment', {
    inverse: null,
    buildReference(db, record) {
			console.log('buildReference', db, record);
      return db.collection('emails').doc(record.get('id')).collection('fragments');
    }
  }),```

**Comment by jernejc** [comment]
Fragment model has a belongsTo.
```
export default DS.Model.extend({
   email: belongsTo('email')
});
```
In db:
![image](https://user-images.githubusercontent.com/1895106/39814566-263b293e-5395-11e8-8723-027bc2b2845c.png)
This feels redundant though, shouldn't it be automatically related to the parent?

Emberfire with the realtime database had a concept of an "embedded" relationship. Where a hasMany was nested inside the root object if set. In Firestore a subcollection seems like a nice way to re-create this, not sure how it would fit in the current setup though.

**Comment by rmmmp** [comment]
Right. That's a bug in the `buildReference` hook. I'll provide a fix today or tomorrow.

As for your other comment, the problem of moving that email under a subcollection will allow you to have duplicate emails.

e.g.

An email at `/fragments/fragment_a/emails/email_a`, `/fragments/fragment_b/emails/email_b`, and `/emails/email_a`.

I'd say avoid directly representing your ember models in a subcollection. If you still wish to do that, then consider not using a relationship and instead `findRecord` that manually.

**Comment by rmmmp** [comment]
@jernejc fixed. You may try it in the master branch while I haven't pushed a bugfix release yet. Feel free to reopen if necessary.

**Comment by jernejc** [comment]
Sorry for the late response. Many thanks! Looks exactly what I need, will test this week.

**Comment by bhernez** [comment]
Hello! I tried to use a sub-collection today without success. This part of the docs didn't happen: `it'll look for the records under the /groups/<group_id>/posts sub-collection`. 

Even when  I wrote a `buildReference` function, the `findRecord` method (I don't know why it gets called), always tried to fetch data from a root-level collection, throwing `Document not found` error.

```
// models/noblyn/course.js
...
posts: DS.hasMany('noblyn/post', {
    inverse: null,
    buildReference(db, record) {
      return db.collection('noblyn-courses').doc(record.get('id')).collection('posts');
    }
  }),
...
```

```
// models/noblyn/post.js
...
course: DS.belongsTo('noblyn/course'),
...
```
<img width="860" alt="captura de pantalla 2018-07-22 a la s 21 53 39" src="https://user-images.githubusercontent.com/1627447/43055078-41cfe67c-8dfa-11e8-9807-1307f9fe4a79.png">
<img width="1140" alt="captura de pantalla 2018-07-22 a la s 21 56 09" src="https://user-images.githubusercontent.com/1627447/43055080-4694ed56-8dfa-11e8-9a8e-0c33cde95a54.png">

**Comment by rmmmp** [comment]
@bhernez this is the first time I've seen a model to be defined under a subdirectory. I'm guessing that it works since you're doing it. Can you try flattening the model directory and see if that'll work? This is so that we can pinpoint the problem.

e.g.

**models/course.js**
**models/post.js**

and 

`posts: DS.hasMany('post', {`
`course: DS.belongsTo('course')`

Lastly, what version of the library are you using?

**Comment by jernejc** [comment]
Only returning to this now, sorry for the late response.
I'm experiencing the same issue that @bhernez is describing.

// document model
```
redactions: DS.hasMany('redaction', {
    inverse: null,

    // Tried with or without "buildReference" function
    buildReference(db, record) {
      return db.collection('documents').doc(record.get('id')).collection('redactions');
    }
})
```

// redaction model
`document: DS.belongsTo('document')`

![screenshot](https://user-images.githubusercontent.com/1895106/44532837-631ee400-a6f4-11e8-82fc-3ec27cbee722.jpg)

Each redaction item in the subcollection also has a document reference field, just in case.

Can't load anything from a subcollection, always looks for a root collection.

Using versions:
"ember-cloud-firestore-adapter": "^0.5.0"
"ember-firebase-service": "^5.0.0"

**Comment by rmmmp** [comment]
What ember data version are you using? Can you set up a test repo that replicates the issue?

**Comment by DavidPhilip** [comment]
For me it looks like the reference is broken as `docSnapshot.get(this.get('referenceKeyName'))` always returns `undefined` and hence it always looks for the subcollection on root level.

I added a fallback to the `ref` property of the docSnapshot for this case in this PR #68 

You can see the structure of the docSnapshots that I'm working with here:
<img width="620" alt="bildschirmfoto 2018-10-20 um 18 55 53" src="https://user-images.githubusercontent.com/2275697/47258365-8539a600-d49a-11e8-8a78-e2c2e7b9b044.png">

Not sure where these changes were made or if it just an issue of configuration on Firestore. I'm new to this so if anyone knows more I'd be glad to update my contribution.

**Comment by rmmmp** [comment]
After investigating this, I remembered that I've done this by design so it's working as expected. See my comment regarding duplicate issue [here](https://github.com/rmmmp/ember-cloud-firestore-adapter/issues/45#issuecomment-387726554).

Using the same example in the link above, there's a chance to have duplicate representations of `email_a` for the `Email` model. This could cause unintended problems.
