### ISSUE TITLE
Authentication?

### ISSUE THREAD

**Issue by jpguzman** [rmmmp/ember-cloud-firestore-adapter#67]
Hey @rmmmp I'm so pumped for the future of Firestore, and I'm so grateful that you took the time to do this! Honestly, I want to start using this right away in a new project.
However, how should I handle authentication?

**Comment by rmmmp** [comment]
That's not part of this addon. You'll either have to implement it on your own or you can use [ember-firebaseui](https://github.com/rmmmp/ember-firebaseui).

**Comment by jpguzman** [comment]
Thanks!
