### ISSUE TITLE
Authentication Integration

### ISSUE THREAD

**Issue by alexmasita** [rmmmp/ember-cloud-firestore-adapter#8]
Great work on this.

Would like to migrate to this from emberfire but has the authentication story been fleshed out?  With emberfire we can add authentication to the app using a torii provider built into EmberFire and the library `emberfire-utils` has a handy addon `firebase-ui-auth` which makes authentication integration a breeze.

**Comment by rmmmp** [comment]
[ember-firebaseui](https://github.com/rmmmp/ember-firebaseui) is what you want if you don't want to roll out your own authentication solution.

**Comment by alexmasita** [comment]
Great!  Will try this out.  Many thanks.
